### ISSUE TITLE
Create the primer binding

### ISSUE THREAD

**Issue by echarles** [datalayer/primer-rjsf#2]
- [x] AddButton
- [x] ArrayFieldItemTemplate
- [x] ArrayFieldTemplate
- [x] BaseInputTemplate
- [x] CheckboxesWidget
- [x] CheckboxWidget
- [x] DateTimeWidget
- [x] DateWidget
- [x] DescriptionField
- [x] ErrorList
- [x] FieldErrorTemplate
- [x] FieldHelpTemplate
- [x] FieldTemplate
- [x] IconButton
- [x] PrimerForm
- [x] ObjectFieldTemplate
- [x] RadioWidget
- [x] RangeWidget (Used mui Slider component)
- [x] SelectWidget
- [x] SubmitButton
- [x] Templates
- [x] TextareaWidget
- [x] Theme
- [x] TitleField
- [x] Widgets
- [x] WrapIfAdditionalTemplate

**Comment by echarles** [comment]
@im-adithya  Looks like your last commit implements this, would be good to double check everything is done by checking the list of widgets in the description of this issue, before closing.

**Comment by im-adithya** [comment]
Done! Double checked ✅
